### ISSUE TITLE
Crashing when opening settings

### ISSUE THREAD

**Issue by VasilisKos** [sal0max/currencies#18] opened 2021-12-13 17:35 UTC
Latest version 1.10.1 crashes when tapping the settings button, on Android 10. I've sent a crash report through Android.

**Comment by sal0max** [comment] 2021-12-13 18:32
Whoops. Thanks for the report!
Was caused by a "harmless" refactoring.

Fixed in 29b5d039191c9ca8f47c738484b843081c77cf21

Should arrive in the stores, soon.

**Closed by sal0max** 2021-12-13 18:32 UTC
