### ISSUE TITLE
Georgian Lari disappeared from the app

### ISSUE THREAD

**Issue by vadiof** [sal0max/currencies#47] opened 2023-03-13 21:23 UTC
Today Georgian Lari disappeared from the app. Nothing helps to get it back: neither changing provider of the rates nor clear cache or storage.
See files attached
![Screenshot_20230314-011522_Currencies](https://user-images.githubusercontent.com/29149307/224835586-ace9af09-78da-4011-9efc-d8373504648d.png)
![Screenshot_20230314-011553_Currencies](https://user-images.githubusercontent.com/29149307/224835599-6b6900bd-44d7-4590-977e-d0d5723f1174.png)

**Comment by sal0max** [comment] 2023-03-14 00:25
This issue was caused by an error in the API: https://github.com/Formicka/exchangerate.host/issues/209

Should be resolved by now. Just refresh your app.

**Closed** 2023-03-14 17:26 UTC
